FROM registry.access.redhat.com/ubi9/ubi:latest AS update
COPY wheels /wheels
RUN python3 -m ensurepip && \
    python3 -m pip install --no-index --find-links=/wheels ruamel.yaml==0.17.9

COPY hack/konflux .
COPY bundle/manifests /manifests/
COPY bundle/metadata /metadata/

RUN source ./container_digest.sh && source ./bundle_vars.sh && python3 ./update_bundle.py

FROM scratch

# Core bundle labels.
LABEL operators.operatorframework.io.bundle.mediatype.v1=registry+v1
LABEL operators.operatorframework.io.bundle.manifests.v1=manifests/
LABEL operators.operatorframework.io.bundle.metadata.v1=metadata/
LABEL operators.operatorframework.io.bundle.package.v1=bgp-cloud-connector
LABEL operators.operatorframework.io.bundle.channels.v1=stable
LABEL operators.operatorframework.io.bundle.channel.default.v1=stable
LABEL operators.operatorframework.io.metrics.builder=operator-sdk-v1.42.2
LABEL operators.operatorframework.io.metrics.mediatype.v1=metrics+v1
LABEL operators.operatorframework.io.metrics.project_layout=go.kubebuilder.io/v4

LABEL maintainer="Red Hat, Inc."
LABEL com.redhat.component="bgp-cloud-connector-bundle"
LABEL name="bgpcc/bgp-cloud-connector-operator-bundle"
LABEL version="0.1.0"
LABEL cpe="cpe:/a:redhat:bgp_cloud_connector:1.0::el9"
LABEL release="0.1.0"
LABEL description="Operator bundle for the BGP cloud connector"
LABEL distribution-scope=public
LABEL url="https://github.com/openshift/bgp-cloud-connector"
LABEL vendor="Red Hat, Inc."
LABEL io.k8s.display-name="BGP cloud connector Operator"
LABEL io.k8s.description="Operator bundle for the BGP cloud connector"
LABEL io.openshift.tags="networking,bgp"

COPY --from=update /manifests /manifests/
COPY --from=update /metadata /metadata/
